serviceAccountName: demo-app
region: eu-west-1

podLabels:
  app: demo-app

service:
  type: NodePort
  port: 8080

readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 30
  successThreshold: 2
  failureThreshold: 2