replicaCount: 1
vaultUrl: https://dev-demo-app.vault.azure.net/
minReplicas: 1
maxReplicas: 2
secretName: dev-demo-app

image:
  repository: 735265414519.dkr.ecr.eu-west-1.amazonaws.com/dev-demo-app
  tag: latest

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

ingress:
  host: "demo-app.azure.rentrahisi.co.ke"