apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: app-secrets
    creationPolicy: Owner