{
 "title": "Kubernetes Dashboard",
 "description": "Monitors Kubernetes cluster using Prometheus. ",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "WORKER NODES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{id=\"/\"}) by (instance) / sum(machine_memory_bytes) by (instance)) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (node))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (\n  node_filesystem_avail_bytes{mountpoint=\"/\", fstype!~\"tmpfs|nfs|rpc_pipefs\"}\n    / node_filesystem_size_bytes{mountpoint=\"/\", fstype!~\"tmpfs|nfs|rpc_pipefs\"} * 100\n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "count(count by (node) (kube_node_info))",
     "legendFormat": "nodes"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (node) (kube_node_info))"
    }
   ]
  },
  {
   "title": "Failed Nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status!=\"true\"})"
    }
   ]
  },
  {
   "title": "Total CPU",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(kube_node_status_allocatable{resource=\"cpu\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(node_memory_MemTotal_bytes) / (1024 * 1024 * 1024))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods per node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (node) (kube_pod_info)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Karpenter NodePool Memory Limit Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "karpenter_nodepool_usage{resource_type=\"memory\"} / karpenter_nodepool_limit{ resource_type=\"memory\"}",
     "legendFormat": "{{resource_type}}"
    }
   ]
  },
  {
   "title": "Karpenter NodePool CPU Limit Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "karpenter_nodepool_usage{resource_type=\"cpu\"} / karpenter_nodepool_limit{ resource_type=\"cpu\"}",
     "legendFormat": "{{resource_type}}"
    }
   ]
  },
  { "title": "PODS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Memory Usage /  Limits by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round(\n  100 *\n    avg(container_memory_working_set_bytes{image!=\"\"}) by (pod, container, namespace)\n      /\n    avg(kube_pod_container_resource_limits{resource=\"memory\"} > 0) by (pod, container, namespace)\n)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Usage / Limits by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round(\n  100 *\n    avg by (pod, container, namespace) (rate(container_cpu_usage_seconds_total[5m]))\n      /\n    avg(kube_pod_container_resource_limits{resource=\"cpu\"} > 0) by (pod, container, namespace)\n)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{ image!=\"\"}[5m])) by (pod) *1000",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Throttled seconds by pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{image!=\"\"}[5m])) by (pod) > 0",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "OOM Events by namespace, pod",
   "type": "timeseries",
   "description": "No data is generally a good thing here.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\"}",
     "legendFormat": "namespace: {{ namespace }} - pod: {{ pod }}"
    }
   ]
  },
  {
   "title": "Container Restarts by namespace, pod",
   "type": "timeseries",
   "description": "No data is generally a good thing here.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total[5m])) by (namespace, pod) > 0",
     "legendFormat": "namespace: {{ namespace }} - pod: {{ pod }}"
    }
   ]
  },
  {
   "title": "Pods by state",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (pod, phase) (kube_pod_status_phase{phase=~\"(Pending|Running|Succeeded|Failed|Unknown)\"})) by (phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod QoS classes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_qos_class) by (qos_class)",
     "legendFormat": "{{ qos_class }} pods"
    },
    { "expr": "sum(kube_pod_info)", "legendFormat": "Total pods" }
   ]
  },
  {
   "title": "Pod per namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(kube_pod_info) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "NAMESPACES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Memory Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\"}) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[5m])) by (namespace) * 1000",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "VOLUMES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": " sum by (persistentvolumeclaim,namespace,storageclass,volumename) (kube_persistentvolumeclaim_info)"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes/1024/1024/1024)"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes/1024/1024/1024)"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_available_bytes/1024/1024/1024)"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=~\"(Pending|Lost)\"}) by (persistentvolumeclaim) + sum(kube_persistentvolumeclaim_status_phase{phase=~\"(Lost)\"}) by (persistentvolumeclaim)"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes/kubelet_volume_stats_capacity_bytes * 100)"
    }
   ]
  }
 ]
}