apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/

commonLabels:
  Environment: dev
  Team: devops

namespace: dev-demo-app

patches:
  - path: deployment-patch.yaml
  - target:
      kind: Namespace
      name: default
    patch: |-
      - op: replace
        path: /metadata/name
        value: dev-demo-app