apiVersion: apps/v1
kind: Deployment
metadata:
  name: rentrahisi
  labels:
    app: rentrahisi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rentrahisi
  template:
    metadata:
      labels:
        app: rentrahisi
    spec:
      containers:
        - name: personal-website
          image: nginx
          ports:
            - containerPort: 80 
          resources:
            requests:
              cpu: 1000m
              memory: 2000Mi
            limits:
              cpu: 1000m
              memory: 2000Mi