apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  annotations:
  {{- range $key, $value := .Values.podAnnotations }}
    {{ $key }}: {{ $value }}
  {{- end }}
    
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- range $key, $value := .Values.podLabels }}
        {{ $key }}: {{ $value }}
      {{- end }}
  template:
    metadata:
      labels:
      {{- range $key, $value := .Values.podLabels }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      {{- if .Values.init_container.create }}
      initContainers:
        - name: {{ .Values.init_container.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: {{ .Values.init_container.command }}
          args: {{ .Values.init_container.args | toYaml | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}
      {{- end }}
      containers:
        - name: {{ .Values.container.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
          - containerPort: {{ .Values.service.port }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.container.command }}
          command: {{ .Values.container.command }}
          {{- end }}
          {{- if .Values.container.args }}
          args: {{ .Values.container.args | toJson }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}
        {{- if eq (int .Values.number_of_containers) 2 }}
        - name: {{ .Values.container_2.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources_2 | nindent 12 }}
          command: {{ .Values.container_2.command }}
          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}
        {{- end }}