apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{ .Values.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: {{ .Values.hpa.resource }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.average_utilization }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300