# {{- if .Values.ingress.enabled }}
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: {{ .Release.Name }}
#   annotations:
#   {{- range $key, $value := .Values.ingress.annotations }}
#     {{ $key }}: {{ $value | quote }}
#   {{- end }}
# spec:
#   tls:
#   - hosts:
#     - {{ .Values.ingress.host }}
#     secretName: "{{ .Release.Name }}-tls-cert"
#   rules:
#   - host: {{ .Values.ingress.host }}
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: {{ .Release.Name }}
#             port:
#               number: {{ .Values.service.port }}
# {{- end }}