# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ .Release.Name }}
# spec:
#   selector:
#     {{- range $key, $value := .Values.podMatchLabels }}
#       {{ $key }}: {{ $value }}
#     {{- end }}
#   ports:
#     - protocol: TCP
#       port: {{ .Values.service.port }}
#       targetPort: {{ .Values.service.port }}
#   type: {{ .Values.service.type }}