name: Deploy Development

on:
  push:
    branches: ["main"]

jobs:
  build-app-image:
    uses: ./.github/workflows/build-app.yml
    with:
      ecr_repo: dev-demo-app
      region: eu-west-1
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-app-infra:
    uses: ./.github/workflows/deploy-app-infra.yml
    with:
      terraform_workspace: dev
    secrets: inherit