name: Deploy Development

on:
  push:
    branches: ["main"]

jobs:
  build-app-image:
    uses: ./.github/workflows/build-app.yml
    with:
      ECR_REPO: dev-demo-app
      REGION: eu-west-1
      DOCKERFILE: demo-app/ 
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}

  deploy-app-infra:
    uses: ./.github/workflows/deploy-infra.yml
    with:
      TERAFORM_WORKSPACE: dev
      WORKING_DIRECTORY: demo-app/terraform
    secrets: inherit